### ISSUE TITLE
aMsgFolder is undefined

### ISSUE THREAD

**Issue by mic-rigaud** [adamnew123456/filterscript#1]
Hello,
You did a very interesting  and a great work. Thank you very much.

However, I have an issue. When the filter is raise, nothing happen. And I have this error:
"The MsgHdrToMimeMessage callback threw an exception: TypeError: aMsgFolder is undefined"

Do you know how to fix it?
Thank you,

ps: thunderbird version: 45.8

**Comment by mic-rigaud** [comment]
I realize un ugly temporaly fix, if that can help...

In fsMessenger.js, I replace:
```
MsgHdrToMimeMessage(header, null, function(header, message) {
                    if (!found_body && message.coerceBodyToPlaintext) {
                        found_body = true;
                        FilterScript.runFilter(message.coerceBodyToPlaintext());
                    }
}, true);
```

with:

     ```
           let uri = header.folder.getUriForMsg(header);
                let messengerer = Components.classes["@mozilla.org/messenger;1"]
                        .createInstance(Components.interfaces.nsIMessenger);
                let listenerer = Components.classes["@mozilla.org/network/sync-stream-listener;1"]
                        .createInstance(Components.interfaces.nsISyncStreamListener);
                messengerer.messageServiceFromURI(uri).streamMessage(uri, listenerer, null, null, false, "");
                let folder = header.folder;
                let messageBody = folder.getMsgTextFromStream(listenerer.inputStream,
                                       header.Charset,
                                       65536,
                                       32768,
                                       false,
                                       true,
                                       { });
                FilterScript.runFilter(messageBody);
```

**Comment by adamnew123456** [comment]
Hey mic, I'm looking into this now. It appears to be something coming from `coerceBodyToPlaintext`, which has something very enlightening to say about the `aMsgFolder` parameter that Filterscript leavs `undefined`:

    * @param aMsgFolder A message folder, any message folder.  Because this is
    *    a hack.

I'll try perusing the Thunderbird source and the documentation a bit further to get an idea of what exactly is going on here, and to see how to obtain a message folder.

That said, I'm having trouble reproducing it. I'm curious what message protocol you're using (IMAP/POP/local mailspool/etc.), if attachments are involved, and if your setup is special in some other way (Enigmail/SMIME, etc.).

EDIT: Also, would the message happen to have an HTML component?

**Comment by adamnew123456** [comment]
Got it, it is a problem with HTML mail. I've got a preliminary fix working, but it has the side effect of adding a bunch of extra spaces to the head of the message. I'll see if I can iron that out before I push.

**Comment by adamnew123456** [comment]
The fix will be landing in master shortly.

The one difference is that the message file is going to contain the full RFC 822 email headers now instead of just the message body - partially because it's more straightforward to get the whole message, and partially because it also opens up new possibilities (like processing attachments) that I want to be available.

**Comment by mic-rigaud** [comment]
Thank you very much. That works fine. :)
